In [47]:
import requests
from bs4 import BeautifulSoup

In [48]:
url="https://pharmeasy.in/health-care?src=header"
r=requests.get(url)

In [49]:
with open("data/main.html","w",encoding="utf-8") as f:
    f.write(r.text)

In [50]:
with open("data/main.html","r") as f:
    html_docs=f.read()
soup=BeautifulSoup(html_docs,"html.parser")

In [51]:
links=[]
def get_links():
    for link in soup.find_all(class_="Category_categoryContainerLandingPageHome__151JB"):
         links.append(link.get("href"))
    return(links)

In [52]:
print(get_links())

['/health-care/top-products-9297', '/health-care/winter-store-16321', '/health-care/fitness-supplements-623', '/health-care/sexual-wellness-575', '/health-care/personal-care-877', '/health-care/health-condition-693', '/health-care/health-food-and-drinks-648', '/health-care/diabetic-care-145', '/health-care/cardiac-store-14374', '/health-care/ayurvedic-care-765', '/health-care/mother-and-baby-care-838', '/health-care/elderly-care-750', '/health-care/sports-nutrition-12931', '/health-care/healthcare-devices-717', '/health-care/skin-care-93', '/health-care/health-essentials-15393']

In [55]:
import os

def get_all_pages(links):
    os.makedirs("data",exist_ok=True)
    
    for i in range(len(links)):
        url=f"https://pharmeasy.in{links[i]}"
        r=requests.get(url)

        if r.status_code==200:
            with open(f"data/page{i}.html","w",encoding="utf-8") as f:
               f.write(r.text)
        else:
            print(f"Failed to fetch {url} | Status: {r.status_code}")

In [56]:
get_all_pages(links)

In [57]:
product_links={}

def product_links_extract():
    
    for i in range(16):
        with open(f"data/page{i}.html","r",encoding="utf-8") as f:
            html_docs=f.read()
            
        soup=BeautifulSoup(html_docs,"html.parser")
        key=f"product_{i}"
        value=[]
        
        for card in soup.find_all(class_="ProductCard_productCardWrapper__x7Ehg"):

            a_tag=card.find("a")
            if a_tag and a_tag.get("href"):
                value.append(a_tag.get("href"))
            
        product_links[key]=(value)
    return product_links

In [58]:
product_links_extract()

{'product_0': ['/health-care/products/pharmeasy-coenzyme-q10-coq10-200mg-with-piperine---for-heart-health-bottle-of-60-capsules-4315302',
  '/health-care/products/pharmeasy-diabetic-protein-powder-french-vanilla-flavour-400g-3963860',
  '/health-care/products/everherb-karela-jamun-juice---helps-maintains-healthy-sugar-levels--helps-in-weight-management---1l--501050',
  '/health-care/products/everherb-diabetic-care-juice-11-potent-ingredients--healthy-blood-sugar-management---1-litre-bottle-3046093',
  '/health-care/products/pharmeasy-pill-box-organizer-234116',
  '/health-care/products/pharmeasy-multivitamin-multimineral---pack-of-60-3491142',
  '/health-care/products/liveasy-foods-healthy-seed-mix-3515408',
  '/health-care/products/everherb-aloe-vera-juice-with-pulp---rejuvenates-skin-hair---1-litre-bottle-501051',
  '/health-care/products/everherb-amla-juice-rich-in-vitamin-c-natural-immunity-booster---1-litre-bottle-501052',
  '/health-care/products/everherb-pain-relief-oil---blend-of-8-powerful-herbal-ingredients---100-ml-501332',
  '/health-care/products/pharmeasy-calcium-magnesium-zinc-vitamin-d3---pack-of-60-3491154',
  '/health-care/products/liveasy-wellness-calcium-magnesium-vitamin-d3-zinc---bones-dental-health---bottle-of-60-tablets-235886',
  '/health-care/products/pharmeasy-fish-oil-1000mg-soft-gelatin-60-capsules-4149275',
  '/health-care/products/everherb-flaxseed-omega-3---essential-fatty-acids---healthy-heart---bottle-of-60-237191',
  '/health-care/products/liveasy-wellness-multivitamin-multimineral---immunity-booster---complete-nutrition---bottle-of-60-235895',
  '/health-care/products/everherb-giloy-tulsi-juice---strengthens-body-defence-system---natural-immunity-booster---1-litre-501053',
  '/health-care/products/everherb-shilajit-500mg---natural-vigour-improvement-capsules---strength-stamina-for-men---bottle-of-60-234976',
  '/health-care/products/liveasy-foods-healthy-seed-mix--blend-of-6-fibre-rich-healthy-seeds-499566',
  '/health-care/products/everherb-ashwagandha---immunity-booster-capsules---anxiety-stress-relief---bottle-of-60-234982',
  '/health-care/products/pharmeasy-biotin---pack-of-60-3491155'],
 'product_1': ['/health-care/products/cetaphil-dam-daily-advance-ultra-hydrating-lotion---100g-40087',
  '/health-care/products/venusia-max-intensive-moisturizing-lotion-for-everyday-use---500g-214676',
  '/health-care/products/supradyn-daily-multivitamin-tablets-15s-3514609',
  '/health-care/products/dabur-yograj-guggulu-120-tablets-172102',
  '/health-care/products/himalaya-ashvagandha-immunity-booster-capsules-bottle-of-60-175663',
  '/health-care/products/nivea-soft-light-moisturizer-of-300-ml-215181',
  '/health-care/products/vaseline-intensive-care-deep-moisture-body-lotion---600-ml-3572832',
  '/health-care/products/cofsils-orange-lozenges-strip-of-10-170274',
  '/health-care/products/vicks-inhaler-keychain-214303',
  '/health-care/products/everherb-karela-jamun-juice---helps-maintains-healthy-sugar-levels--helps-in-weight-management---1l--501050',
  '/health-care/products/everherb-diabetic-care-juice-11-potent-ingredients--healthy-blood-sugar-management---1-litre-bottle-3046093',
  '/health-care/products/saridon-new-50-mg-500-mg-tablets-10-3994961',
  '/health-care/products/crocin-pain-relief-strip-of-15-tablets-171921',
  '/health-care/products/cofsils-ginger-lemon-lozenges-strip-of-10-6939',
  '/health-care/products/scalpe-plus-anti-dandruff-shampoo-bottle-of-75-ml-11943',
  '/health-care/products/volini-pain-relief-gel-tube-of-75-g-22736',
  '/health-care/products/pharmeasy-multivitamin-multimineral---pack-of-60-3491142',
  '/health-care/products/everherb-aloe-vera-juice-with-pulp---rejuvenates-skin-hair---1-litre-bottle-501051',
  '/health-care/products/supradyn-daily-multivitamin-for-men-women-builds-energy-immunity-botle-of-60-multivitamin-tablet-4034333',
  '/health-care/products/everherb-amla-juice-rich-in-vitamin-c-natural-immunity-booster---1-litre-bottle-501052'],
 'product_2': ['/health-care/products/pharmeasy-multivitamin-multimineral---pack-of-60-3491142',
  '/health-care/products/shelcal-500mg-strip-of-15-tablets-9033',
  '/health-care/products/pharmeasy-multivitamin-women---bottle-of-60-3662202',
  '/health-care/products/supradyn-daily-multivitamin-tablets-15s-3514609',
  '/health-care/products/zincovit-strip-of-15-tablets-green--3318',
  '/health-care/products/evion-400mg-strip-of-20-capsule-3110481',
  '/health-care/products/everherb-karela-jamun-juice---helps-maintains-healthy-sugar-levels--helps-in-weight-management---1l--501050',
  '/health-care/products/calcimax-forte-plus-strip-of-30-tablets-19501',
  '/health-care/products/everherb-diabetic-care-juice-11-potent-ingredients--healthy-blood-sugar-management---1-litre-bottle-3046093',
  '/health-care/products/calcimax-500-health-supplement-tablets-500-mg-of-calcium-box-of-30-38706',
  '/health-care/products/evion-600mg-strip-of-10-capsules-46327',
  '/health-care/products/depura-60k-nano-vit-d-vitamin-drops-sugar-free-bottle-of-5-ml-24055',
  '/health-care/products/arachitol-nano-60k-sugar-free-bottle-of-5ml-solution-209565',
  '/health-care/products/calcimax-p-susp-38711',
  '/health-care/products/livogen-z-captab-15-s-206637',
  '/health-care/products/becozym-c-forte-strip-of-20-tablets-4130516',
  '/health-care/products/shelcal-250mg-tablet-9030',
  '/health-care/products/evion-200mg-strip-of-10-capsules-8720',
  '/health-care/products/supradyn-daily-multivitamin-for-men-women-builds-energy-immunity-botle-of-60-multivitamin-tablet-4034333',
  '/health-care/products/sevenseas-original-capsule-100-s-19300'],
 'product_3': ['/health-care/products/everherb-shilajit-500mg---natural-vigour-improvement-capsules---strength-stamina-for-men---bottle-of-60-234976',
  '/health-care/products/mankind-at-home-one-step-urine-hcg-pregnancy-test-kit-10-tests--4003147',
  '/health-care/products/everherb-men-s-formula---blend-of-6-safe-powerful-herb---increase-sperm-count---bottle-of-60-234977',
  '/health-care/products/manforce-cocktail-condoms-combo-strawberry-vanilla-chocolate-hazelnut-pack-of-4-40-condoms--4003026',
  '/health-care/products/ved-tattva-safed-musli-powder---1-kg-pack-of-2--3812745',
  '/health-care/products/mankind-at-home-one-step-urine-hcg-digital-pregnancy-test-kit-6-tests--4003146',
  '/health-care/products/manforce-cocktail-condoms-dotted-rings-hazelnut-chocolate-flavoured-10-pcs-x-pack-of-4-4002830',
  '/health-care/products/manforce-epic-strawberry-flavored-lube-60-ml-x-pack-of-4-4003124',
  '/health-care/products/manforce-cocktail-strawberry-vanilla-3-in-1-overtime-orange-flavoured-condoms-set-of-2-20-pcs--4003032',
  '/health-care/products/skore-condoms-assorted-flavoured-and-coloured-1500-raised-dots-with-extra-lubrication-box-of-20-3930901',
  '/health-care/products/manforce-chocolate-flavor-condom-10-pcs-x-pack-of-5-4002828',
  '/health-care/products/manforce-cocktail-condoms-dotted-rings-strawberry-vanilla-flavoured-10-pcs-x-pack-of-5-4002833',
  '/health-care/products/manforce-epic-fruit-pack-10s-pack-of-2--4002850',
  '/health-care/products/manforce-overtime-pineapple-condoms-10-pcs-x-pack-of-4-4002868',
  '/health-care/products/manforce-staylong-orange-flav-condom-3-s-194724',
  '/health-care/products/manforce-condoms-3-in-1-ribbed-contour-dotted-strawberry-flavoured-condoms---10-pcs-x-pack-of-5-4002841',
  '/health-care/products/manforce-condoms-assorted-flavour-10-pcs-x-pack-of-4-4002842',
  '/health-care/products/durex-mutual-climax-condoms-for-men-women---10-count-with-durex-water-based-lube-cherry-3709128',
  '/health-care/products/manforce-wild-condoms-strawberry---super-saver-2-x-20s--216636',
  '/health-care/products/manforce-condoms-assorted-flavour-10-pcs-x-pack-of-5-4002843'],
 'product_4': ['/health-care/products/calcimax-500-health-supplement-tablets-500-mg-of-calcium-box-of-30-38706',
  '/health-care/products/refresh-tears-0-5-bottle-of-10ml-eye-drops-2967',
  '/health-care/products/episoft-ac-sunscreen-spf30-lotion-75gm-12004',
  '/health-care/products/bontress-pro-scalp-serum-bottle-of-60ml-4051984',
  '/health-care/products/pharmeasy-biotin---pack-of-60-3491155',
  '/health-care/products/scalpe-plus-anti-dandruff-shampoo-bottle-of-75-ml-11943',
  '/health-care/products/pharmeasy-multivitamin-multimineral---pack-of-60-3491142',
  '/health-care/products/liveasy-foods-healthy-seed-mix-3515408',
  '/health-care/products/everherb-aloe-vera-juice-with-pulp---rejuvenates-skin-hair---1-litre-bottle-501051',
  '/health-care/products/everherb-pain-relief-oil---blend-of-8-powerful-herbal-ingredients---100-ml-501332',
  '/health-care/products/pharmeasy-calcium-magnesium-zinc-vitamin-d3---pack-of-60-3491154',
  '/health-care/products/venusia-max-intensive-moisturizing-lotion-for-everyday-use---500g-214676',
  '/health-care/products/photostable-gold-spf55-sunscreen-gel-50g-212108',
  '/health-care/products/liveasy-wellness-calcium-magnesium-vitamin-d3-zinc---bones-dental-health---bottle-of-60-tablets-235886',
  '/health-care/products/venusia-max-intensive-moisturizing-cream-for-dry-very-dry-skin-tube-of-150-g-8293',
  '/health-care/products/mildy-shampoo-100ml-13949',
  '/health-care/products/pharmeasy-fish-oil-1000mg-soft-gelatin-60-capsules-4149275',
  '/health-care/products/everherb-flaxseed-omega-3---essential-fatty-acids---healthy-heart---bottle-of-60-237191',
  '/health-care/products/liveasy-wellness-multivitamin-multimineral---immunity-booster---complete-nutrition---bottle-of-60-235895',
  '/health-care/products/cetaphil-gentle-skin-cleanser---125ml-11064'],
 'product_5': ['/health-care/products/digene-insta-on-the-go-mint-10ml-pack-of-5--4385408',
  '/health-care/products/everherb-karela-jamun-juice---helps-maintains-healthy-sugar-levels--helps-in-weight-management---1l--501050',
  '/health-care/products/oxalgin-nano-gel-30gm-30829',
  '/health-care/products/digene-acidity-gas-relief-tablets-15s--mint-flavour-846',
  '/health-care/products/cofsils-orange-lozenges-strip-of-10-170274',
  '/health-care/products/everherb-diabetic-care-juice-11-potent-ingredients--healthy-blood-sugar-management---1-litre-bottle-3046093',
  '/health-care/products/evion-l-5000-strip-of-15-capsules-4497227',
  '/health-care/products/candid-dusting-powder---120-gm-3110769',
  '/health-care/products/saridon-new-50-mg-500-mg-tablets-10-3994961',
  '/health-care/products/unienzyme-strip-of-15-tablets-27680',
  '/health-care/products/crocin-pain-relief-strip-of-15-tablets-171921',
  '/health-care/products/refresh-tears-0-5-bottle-of-10ml-eye-drops-2967',
  '/health-care/products/gelusil-mps-original-mint-flavour-tablet-15-s-231695',
  '/health-care/products/cofsils-ginger-lemon-lozenges-strip-of-10-6939',
  '/health-care/products/gas-o-fast-active-jeera-antacid-sachet-of-5-g-208807',
  '/health-care/products/abzorb-total-skin-relief-dusting-powder-20-extra-bottle-of-120gm-4151486',
  '/health-care/products/volini-pain-relief-gel-tube-of-75-g-22736',
  '/health-care/products/himalaya-liv-52-ds-tablets---60-s-12836',
  '/health-care/products/eno-fruit-lemon-salt-sach-5gm-11508',
  '/health-care/products/digene-acidity-gas-relief-tablets-15s--orange-flavour-856'],
 'product_6': ['/health-care/products/shelcal-500mg-strip-of-15-tablets-9033',
  '/health-care/products/everherb-diabetic-care-juice-11-potent-ingredients--healthy-blood-sugar-management---1-litre-bottle-3046093',
  '/health-care/products/ensure-diabetes-care-specialized-nutrition-drink-vanilla-950g-4222936',
  '/health-care/products/supradyn-daily-multivitamin-tablets-15s-3514609',
  '/health-care/products/nutty-gritties-roasted-pumpkin-seeds-unsalted---200g-4342538',
  '/health-care/products/organic-india-tulsi-ginger-turmeric-tea-bag-25-s-213198',
  '/health-care/products/pharmeasy-daily-protein---provides-energy-vitality---jar-of-400-gram-3884468',
  '/health-care/products/zincovit-strip-of-15-tablets-green--3318',
  '/health-care/products/evion-400mg-strip-of-20-capsule-3110481',
  '/health-care/products/everherb-karela-jamun-juice---helps-maintains-healthy-sugar-levels--helps-in-weight-management---1l--501050',
  '/health-care/products/calcimax-forte-plus-strip-of-30-tablets-19501',
  '/health-care/products/calcimax-500-health-supplement-tablets-500-mg-of-calcium-box-of-30-38706',
  '/health-care/products/evion-600mg-strip-of-10-capsules-46327',
  '/health-care/products/depura-60k-nano-vit-d-vitamin-drops-sugar-free-bottle-of-5-ml-24055',
  '/health-care/products/arachitol-nano-60k-sugar-free-bottle-of-5ml-solution-209565',
  '/health-care/products/calcimax-p-susp-38711',
  '/health-care/products/becozym-c-forte-strip-of-20-tablets-4130516',
  '/health-care/products/pharmeasy-multivitamin-multimineral---pack-of-60-3491142',
  '/health-care/products/shelcal-250mg-tablet-9030',
  '/health-care/products/evion-200mg-strip-of-10-capsules-8720'],
 'product_7': ['/health-care/products/everherb-diabetic-care-juice-11-potent-ingredients--healthy-blood-sugar-management---1-litre-bottle-3046093',
  '/health-care/products/sugar-free-gold-sweetener-powder-jar-of-100-g-218854',
  '/health-care/products/everherb-diabetic-care---7-specially-researched-ayurvedic-herbs---blood-sugar-control---bottle-of-60-235318',
  '/health-care/products/everherb-karela-jamun-juice---helps-maintains-healthy-sugar-levels--helps-in-weight-management---1l--501050',
  '/health-care/products/dr-morepen-gluco-one-bg-03-glucometer-test-strips-box-of-50-172151',
  '/health-care/products/accu-chek-active-glucometer-test-strips-box-of-50-172157',
  '/health-care/products/pharmeasy-diabetic-protein-powder-chocolate-flavour-400g-3963859',
  '/health-care/products/accu-chek-instant-glucometer-test-strips-box-of-50-206937',
  '/health-care/products/liveasy-foods-healthy-seed-mix-3515408',
  '/health-care/products/gelusil-mps-mint-flavour-sugar-free-bottle-of-400ml-liquid-208203',
  '/health-care/products/everherb-flaxseed-omega-3---essential-fatty-acids---healthy-heart---bottle-of-60-237191',
  '/health-care/products/contour-plus-glucometer-test-strips-box-of-50-4461',
  '/health-care/products/liveasy-foods-healthy-seed-mix--blend-of-6-fibre-rich-healthy-seeds-499566',
  '/health-care/products/one-touch-select-glucometer-test-strips-bottle-of-50-15466',
  '/health-care/products/pharmeasy-apple-cider-vinegar-with-mother--improves-metabolism--500ml-bottle-3864231',
  '/health-care/products/accu-chek-active-glucometer-test-strips-box-of-100-172158',
  '/health-care/products/digene-gel-acidity-gas-relief---200ml-mint-flavour-172824',
  '/health-care/products/cremaffin-constipation-relief-syrup-mint-225ml-175750',
  '/health-care/products/one-touch-select-plus-glucometer-test-strips-box-of-50-230432',
  '/health-care/products/sugar-free-gold-pellet-500-no-s-3669245'],
 'product_8': ['/health-care/products/pharmeasy-coenzyme-q10-coq10-200mg-with-piperine---for-heart-health-bottle-of-60-capsules-4315302',
  '/health-care/products/pharmeasy-fish-oil-1000mg-soft-gelatin-60-capsules-4149275',
  '/health-care/products/everherb-flaxseed-omega-3---essential-fatty-acids---healthy-heart---bottle-of-60-237191',
  '/health-care/products/seacod-cap-100-s-23935',
  '/health-care/products/pharmeasy-apple-cider-vinegar-with-mother--improves-metabolism--500ml-bottle-3864231',
  '/health-care/products/everherb-fat-burner---natural-herbal-blend---accelerates-calorie-burning---bottle-of-60-237462',
  '/health-care/products/hima-arjuna-tablet-60-s-12828',
  '/health-care/products/wow-life-science-omega-3-capsules-bottle-of-60-237224',
  '/health-care/products/omron-hem-7120-bp-monitor-175456',
  '/health-care/products/baidyanath-nagpur-amla-juice---natural-immunity-booster-enriched-with-vitamin-c---1-ltr-3688561',
  '/health-care/products/briyo-fish-oil-mini-450-mg-size--60-softgels---71-39-omega-3-320-mg-omega-3-per-450-mg-capsule-3737089',
  '/health-care/products/healthkart-hk-vitals-fish-oil-capsule-1000mg-omega-3-180-mg-epa-120-mg-dha-90-capsules-3900337',
  '/health-care/products/omron-hem-7124-bp-monitor-223948',
  '/health-care/products/himalaya-lasuna-tablets---60-s-12897',
  '/health-care/products/healthkart-hk-vitals-fish-oil-1000mg-with-180mg-epa-and-120mg-dha-60-capsules-3828218',
  '/health-care/products/dr-morepen-bp-15-bp-monitor-3572012',
  '/health-care/products/seacod-cod-liver-oil-bottle-of-60-ml-24034',
  '/health-care/products/dr-morepen-omega-3-deep-sea-fish-oil-triple-strength-capsules-for-healthy-heart-brain-joints---60-softgels-3512184',
  '/health-care/products/accusure-as-bp-digital-monitor-3012587',
  '/health-care/products/kapiva-dia-free-juice-2l-for-holistic-diabetes-care-amla-karela-9-more---super-saver-pack-of-2-3864283'],
 'product_9': ['/health-care/products/everherb-karela-jamun-juice---helps-maintains-healthy-sugar-levels--helps-in-weight-management---1l--501050',
  '/health-care/products/healthvit-keto-fat-burner-formulated-in-usa-with-garcinia-green-tea-green-coffee-cla--60-capsules-502201',
  '/health-care/products/everherb-giloy-tulsi-juice---strengthens-body-defence-system---natural-immunity-booster---1-litre-501053',
  '/health-care/products/himalaya-liv-52-tablet-pack-of-2-3884334',
  '/health-care/products/everherb-amla-juice-rich-in-vitamin-c-natural-immunity-booster---1-litre-bottle-501052',
  '/health-care/products/herbal-hills-gotu-kola-powder---1-kg-3808960',
  '/health-care/products/torliv-200ml-pack-of-6-4075684',
  '/health-care/products/herbal-hills-guduchi-powder---1kg---pack-of-2-3628748',
  '/health-care/products/healthvit-ginger-powder-250-mg--60-capsules-502194',
  '/health-care/products/kerala-ayurveda-ajax-vigor-improvement-capsules-box-of-50-s-216505',
  '/health-care/products/dr-vaidya-s-herbo24turbo-capsules-ayurvedic-shilajit-vitalizer-for-men-30-capsules-216335',
  '/health-care/products/herbal-hills-turmeric-powder---1kg---pack-of-2-3629912',
  '/health-care/products/dr-vaidya-s-cycloherb-capsule-30-3018418',
  '/health-care/products/axiom-karela-jamun-swaras-500-ml-3027230',
  '/health-care/products/torliv-200ml-pack-of-3-4075683',
  '/health-care/products/hass-shunthi-churna---shunthi-powder---dry-ginger-powder--for-tea-for-throat-1x500-gram--3825744',
  '/health-care/products/herbal-hills-nagarmotha-powder---1kg---pack-of-2-3628852',
  '/health-care/products/anuja-actiliv-forte-tablet---60-tab-pack-of-2--3789527',
  '/health-care/products/dr-vaidya-s-cycloherb--for-supporting-female-reproductive-health-30-capsules-x-2--3113918',
  '/health-care/products/organic-india-assam-black-tea-50-tea-bags-4337954'],
 'product_10': ['/health-care/products/equalstwo-baby-skin-healing-cream-150-gm-3845815',
  '/health-care/products/equalstwo-baby-moisturizer-200-ml-3845371',
  '/health-care/products/prega-news-pregnancy-test-kit-177505',
  '/health-care/products/ultra-d3-drops---vitamin-d3-for-infants-vitamin-drops-bottle-of-15-ml-227487',
  '/health-care/products/i-can-pregnancy-test-kit-88380',
  '/health-care/products/tedibar-baby-soap-box-of-75-g-x-2-235076',
  '/health-care/products/new-atogla-baby-moisturizing-lotion-bottle-of-200-ml-3754509',
  '/health-care/products/ferronomic-plus-tablet-15-no-s-4085848',
  '/health-care/products/himalaya-baby-powder-bottle-of-400-g-175638',
  '/health-care/products/prohance-mom-chocolate-nutrition-drink-jar-of-400-g-193671',
  '/health-care/products/sebamed-baby-cleansing-bar---100g-28421',
  '/health-care/products/tedibar-bathing-bar-75gm-7483',
  '/health-care/products/enterogermina-probiotic-supplement-for-diarrhea-treatment-restoration-of-gut-flora-for-kids-adults-oral-use---2-strips-4-capsules-each--45590',
  '/health-care/products/pharmeasy-multivitamin-gummies-3626268',
  '/health-care/products/spoo-shampoo-bottle-of-125-ml-192679',
  '/health-care/products/b4-nappi-baby-rash-cream-tube-of-75-g-7497',
  '/health-care/products/tedibar-baby-soap-box-of-75-g-x-3-2982412',
  '/health-care/products/aptamil-stage-1-infant-formula-baby-food-tin-of-400-g-192264',

In [59]:
all_links=[]

for values in product_links.values():
    all_links.extend(values)

In [60]:
all_links

['/health-care/products/pharmeasy-coenzyme-q10-coq10-200mg-with-piperine---for-heart-health-bottle-of-60-capsules-4315302',
 '/health-care/products/pharmeasy-diabetic-protein-powder-french-vanilla-flavour-400g-3963860',
 '/health-care/products/everherb-karela-jamun-juice---helps-maintains-healthy-sugar-levels--helps-in-weight-management---1l--501050',
 '/health-care/products/everherb-diabetic-care-juice-11-potent-ingredients--healthy-blood-sugar-management---1-litre-bottle-3046093',
 '/health-care/products/pharmeasy-pill-box-organizer-234116',
 '/health-care/products/pharmeasy-multivitamin-multimineral---pack-of-60-3491142',
 '/health-care/products/liveasy-foods-healthy-seed-mix-3515408',
 '/health-care/products/everherb-aloe-vera-juice-with-pulp---rejuvenates-skin-hair---1-litre-bottle-501051',
 '/health-care/products/everherb-amla-juice-rich-in-vitamin-c-natural-immunity-booster---1-litre-bottle-501052',
 '/health-care/products/everherb-pain-relief-oil---blend-of-8-powerful-herbal-ingredients---100-ml-501332',
 '/health-care/products/pharmeasy-calcium-magnesium-zinc-vitamin-d3---pack-of-60-3491154',
 '/health-care/products/liveasy-wellness-calcium-magnesium-vitamin-d3-zinc---bones-dental-health---bottle-of-60-tablets-235886',
 '/health-care/products/pharmeasy-fish-oil-1000mg-soft-gelatin-60-capsules-4149275',
 '/health-care/products/everherb-flaxseed-omega-3---essential-fatty-acids---healthy-heart---bottle-of-60-237191',
 '/health-care/products/liveasy-wellness-multivitamin-multimineral---immunity-booster---complete-nutrition---bottle-of-60-235895',
 '/health-care/products/everherb-giloy-tulsi-juice---strengthens-body-defence-system---natural-immunity-booster---1-litre-501053',
 '/health-care/products/everherb-shilajit-500mg---natural-vigour-improvement-capsules---strength-stamina-for-men---bottle-of-60-234976',
 '/health-care/products/liveasy-foods-healthy-seed-mix--blend-of-6-fibre-rich-healthy-seeds-499566',
 '/health-care/products/everherb-ashwagandha---immunity-booster-capsules---anxiety-stress-relief---bottle-of-60-234982',
 '/health-care/products/pharmeasy-biotin---pack-of-60-3491155',
 '/health-care/products/cetaphil-dam-daily-advance-ultra-hydrating-lotion---100g-40087',
 '/health-care/products/venusia-max-intensive-moisturizing-lotion-for-everyday-use---500g-214676',
 '/health-care/products/supradyn-daily-multivitamin-tablets-15s-3514609',
 '/health-care/products/dabur-yograj-guggulu-120-tablets-172102',
 '/health-care/products/himalaya-ashvagandha-immunity-booster-capsules-bottle-of-60-175663',
 '/health-care/products/nivea-soft-light-moisturizer-of-300-ml-215181',
 '/health-care/products/vaseline-intensive-care-deep-moisture-body-lotion---600-ml-3572832',
 '/health-care/products/cofsils-orange-lozenges-strip-of-10-170274',
 '/health-care/products/vicks-inhaler-keychain-214303',
 '/health-care/products/everherb-karela-jamun-juice---helps-maintains-healthy-sugar-levels--helps-in-weight-management---1l--501050',
 '/health-care/products/everherb-diabetic-care-juice-11-potent-ingredients--healthy-blood-sugar-management---1-litre-bottle-3046093',
 '/health-care/products/saridon-new-50-mg-500-mg-tablets-10-3994961',
 '/health-care/products/crocin-pain-relief-strip-of-15-tablets-171921',
 '/health-care/products/cofsils-ginger-lemon-lozenges-strip-of-10-6939',
 '/health-care/products/scalpe-plus-anti-dandruff-shampoo-bottle-of-75-ml-11943',
 '/health-care/products/volini-pain-relief-gel-tube-of-75-g-22736',
 '/health-care/products/pharmeasy-multivitamin-multimineral---pack-of-60-3491142',
 '/health-care/products/everherb-aloe-vera-juice-with-pulp---rejuvenates-skin-hair---1-litre-bottle-501051',
 '/health-care/products/supradyn-daily-multivitamin-for-men-women-builds-energy-immunity-botle-of-60-multivitamin-tablet-4034333',
 '/health-care/products/everherb-amla-juice-rich-in-vitamin-c-natural-immunity-booster---1-litre-bottle-501052',
 '/health-care/products/pharmeasy-multivitamin-multimineral---pack-of-60-3491142',
 '/health-care/products/shelcal-500mg-strip-of-15-tablets-9033',
 '/health-care/products/pharmeasy-multivitamin-women---bottle-of-60-3662202',
 '/health-care/products/supradyn-daily-multivitamin-tablets-15s-3514609',
 '/health-care/products/zincovit-strip-of-15-tablets-green--3318',
 '/health-care/products/evion-400mg-strip-of-20-capsule-3110481',
 '/health-care/products/everherb-karela-jamun-juice---helps-maintains-healthy-sugar-levels--helps-in-weight-management---1l--501050',
 '/health-care/products/calcimax-forte-plus-strip-of-30-tablets-19501',
 '/health-care/products/everherb-diabetic-care-juice-11-potent-ingredients--healthy-blood-sugar-management---1-litre-bottle-3046093',
 '/health-care/products/calcimax-500-health-supplement-tablets-500-mg-of-calcium-box-of-30-38706',
 '/health-care/products/evion-600mg-strip-of-10-capsules-46327',
 '/health-care/products/depura-60k-nano-vit-d-vitamin-drops-sugar-free-bottle-of-5-ml-24055',
 '/health-care/products/arachitol-nano-60k-sugar-free-bottle-of-5ml-solution-209565',
 '/health-care/products/calcimax-p-susp-38711',
 '/health-care/products/livogen-z-captab-15-s-206637',
 '/health-care/products/becozym-c-forte-strip-of-20-tablets-4130516',
 '/health-care/products/shelcal-250mg-tablet-9030',
 '/health-care/products/evion-200mg-strip-of-10-capsules-8720',
 '/health-care/products/supradyn-daily-multivitamin-for-men-women-builds-energy-immunity-botle-of-60-multivitamin-tablet-4034333',
 '/health-care/products/sevenseas-original-capsule-100-s-19300',
 '/health-care/products/everherb-shilajit-500mg---natural-vigour-improvement-capsules---strength-stamina-for-men---bottle-of-60-234976',
 '/health-care/products/mankind-at-home-one-step-urine-hcg-pregnancy-test-kit-10-tests--4003147',
 '/health-care/products/everherb-men-s-formula---blend-of-6-safe-powerful-herb---increase-sperm-count---bottle-of-60-234977',
 '/health-care/products/manforce-cocktail-condoms-combo-strawberry-vanilla-chocolate-hazelnut-pack-of-4-40-condoms--4003026',
 '/health-care/products/ved-tattva-safed-musli-powder---1-kg-pack-of-2--3812745',
 '/health-care/products/mankind-at-home-one-step-urine-hcg-digital-pregnancy-test-kit-6-tests--4003146',
 '/health-care/products/manforce-cocktail-condoms-dotted-rings-hazelnut-chocolate-flavoured-10-pcs-x-pack-of-4-4002830',
 '/health-care/products/manforce-epic-strawberry-flavored-lube-60-ml-x-pack-of-4-4003124',
 '/health-care/products/manforce-cocktail-strawberry-vanilla-3-in-1-overtime-orange-flavoured-condoms-set-of-2-20-pcs--4003032',
 '/health-care/products/skore-condoms-assorted-flavoured-and-coloured-1500-raised-dots-with-extra-lubrication-box-of-20-3930901',
 '/health-care/products/manforce-chocolate-flavor-condom-10-pcs-x-pack-of-5-4002828',
 '/health-care/products/manforce-cocktail-condoms-dotted-rings-strawberry-vanilla-flavoured-10-pcs-x-pack-of-5-4002833',
 '/health-care/products/manforce-epic-fruit-pack-10s-pack-of-2--4002850',
 '/health-care/products/manforce-overtime-pineapple-condoms-10-pcs-x-pack-of-4-4002868',
 '/health-care/products/manforce-staylong-orange-flav-condom-3-s-194724',
 '/health-care/products/manforce-condoms-3-in-1-ribbed-contour-dotted-strawberry-flavoured-condoms---10-pcs-x-pack-of-5-4002841',
 '/health-care/products/manforce-condoms-assorted-flavour-10-pcs-x-pack-of-4-4002842',
 '/health-care/products/durex-mutual-climax-condoms-for-men-women---10-count-with-durex-water-based-lube-cherry-3709128',
 '/health-care/products/manforce-wild-condoms-strawberry---super-saver-2-x-20s--216636',
 '/health-care/products/manforce-condoms-assorted-flavour-10-pcs-x-pack-of-5-4002843',
 '/health-care/products/calcimax-500-health-supplement-tablets-500-mg-of-calcium-box-of-30-38706',
 '/health-care/products/refresh-tears-0-5-bottle-of-10ml-eye-drops-2967',
 '/health-care/products/episoft-ac-sunscreen-spf30-lotion-75gm-12004',
 '/health-care/products/bontress-pro-scalp-serum-bottle-of-60ml-4051984',
 '/health-care/products/pharmeasy-biotin---pack-of-60-3491155',
 '/health-care/products/scalpe-plus-anti-dandruff-shampoo-bottle-of-75-ml-11943',
 '/health-care/products/pharmeasy-multivitamin-multimineral---pack-of-60-3491142',
 '/health-care/products/liveasy-foods-healthy-seed-mix-3515408',
 '/health-care/products/everherb-aloe-vera-juice-with-pulp---rejuvenates-skin-hair---1-litre-bottle-501051',
 '/health-care/products/everherb-pain-relief-oil---blend-of-8-powerful-herbal-ingredients---100-ml-501332',
 '/health-care/products/pharmeasy-calcium-magnesium-zinc-vitamin-d3---pack-of-60-3491154',
 '/health-care/products/venusia-max-intensive-moisturizing-lotion-for-everyday-use---500g-214676',
 '/health-care/products/photostable-gold-spf55-sunscreen-gel-50g-212108',
 '/health-care/products/liveasy-wellness-calcium-magnesium-vitamin-d3-zinc---bones-dental-health---bottle-of-60-tablets-235886',
 '/health-care/products/venusia-max-intensive-moisturizing-cream-for-dry-very-dry-skin-tube-of-150-g-8293',
 '/health-care/products/mildy-shampoo-100ml-13949',
 '/health-care/products/pharmeasy-fish-oil-1000mg-soft-gelatin-60-capsules-4149275',
 '/health-care/products/everherb-flaxseed-omega-3---essential-fatty-acids---healthy-heart---bottle-of-60-237191',
 '/health-care/products/liveasy-wellness-multivitamin-multimineral---immunity-booster---complete-nutrition---bottle-of-60-235895',
 '/health-care/products/cetaphil-gentle-skin-cleanser---125ml-11064',
 '/health-care/products/digene-insta-on-the-go-mint-10ml-pack-of-5--4385408',
 '/health-care/products/everherb-karela-jamun-juice---helps-maintains-healthy-sugar-levels--helps-in-weight-management---1l--501050',
 '/health-care/products/oxalgin-nano-gel-30gm-30829',
 '/health-care/products/digene-acidity-gas-relief-tablets-15s--mint-flavour-846',
 '/health-care/products/cofsils-orange-lozenges-strip-of-10-170274',
 '/health-care/products/everherb-diabetic-care-juice-11-potent-ingredients--healthy-blood-sugar-management---1-litre-bottle-3046093',
 '/health-care/products/evion-l-5000-strip-of-15-capsules-4497227',
 '/health-care/products/candid-dusting-powder---120-gm-3110769',
 '/health-care/products/saridon-new-50-mg-500-mg-tablets-10-3994961',
 '/health-care/products/unienzyme-strip-of-15-tablets-27680',
 '/health-care/products/crocin-pain-relief-strip-of-15-tablets-171921',
 '/health-care/products/refresh-tears-0-5-bottle-of-10ml-eye-drops-2967',
 '/health-care/products/gelusil-mps-original-mint-flavour-tablet-15-s-231695',
 '/health-care/products/cofsils-ginger-lemon-lozenges-strip-of-10-6939',
 '/health-care/products/gas-o-fast-active-jeera-antacid-sachet-of-5-g-208807',
 '/health-care/products/abzorb-total-skin-relief-dusting-powder-20-extra-bottle-of-120gm-4151486',
 '/health-care/products/volini-pain-relief-gel-tube-of-75-g-22736',
 '/health-care/products/himalaya-liv-52-ds-tablets---60-s-12836',
 '/health-care/products/eno-fruit-lemon-salt-sach-5gm-11508',
 '/health-care/products/digene-acidity-gas-relief-tablets-15s--orange-flavour-856',
 '/health-care/products/shelcal-500mg-strip-of-15-tablets-9033',
 '/health-care/products/everherb-diabetic-care-juice-11-potent-ingredients--healthy-blood-sugar-management---1-litre-bottle-3046093',
 '/health-care/products/ensure-diabetes-care-specialized-nutrition-drink-vanilla-950g-4222936',
 '/health-care/products/supradyn-daily-multivitamin-tablets-15s-3514609',
 '/health-care/products/nutty-gritties-roasted-pumpkin-seeds-unsalted---200g-4342538',
 '/health-care/products/organic-india-tulsi-ginger-turmeric-tea-bag-25-s-213198',
 '/health-care/products/pharmeasy-daily-protein---provides-energy-vitality---jar-of-400-gram-3884468',
 '/health-care/products/zincovit-strip-of-15-tablets-green--3318',
 '/health-care/products/evion-400mg-strip-of-20-capsule-3110481',
 '/health-care/products/everherb-karela-jamun-juice---helps-maintains-healthy-sugar-levels--helps-in-weight-management---1l--501050',
 '/health-care/products/calcimax-forte-plus-strip-of-30-tablets-19501',
 '/health-care/products/calcimax-500-health-supplement-tablets-500-mg-of-calcium-box-of-30-38706',
 '/health-care/products/evion-600mg-strip-of-10-capsules-46327',
 '/health-care/products/depura-60k-nano-vit-d-vitamin-drops-sugar-free-bottle-of-5-ml-24055',
 '/health-care/products/arachitol-nano-60k-sugar-free-bottle-of-5ml-solution-209565',
 '/health-care/products/calcimax-p-susp-38711',
 '/health-care/products/becozym-c-forte-strip-of-20-tablets-4130516',
 '/health-care/products/pharmeasy-multivitamin-multimineral---pack-of-60-3491142',
 '/health-care/products/shelcal-250mg-tablet-9030',
 '/health-care/products/evion-200mg-strip-of-10-capsules-8720',
 '/health-care/products/everherb-diabetic-care-juice-11-potent-ingredients--healthy-blood-sugar-management---1-litre-bottle-3046093',
 '/health-care/products/sugar-free-gold-sweetener-powder-jar-of-100-g-218854',
 '/health-care/products/everherb-diabetic-care---7-specially-researched-ayurvedic-herbs---blood-sugar-control---bottle-of-60-235318',
 '/health-care/products/everherb-karela-jamun-juice---helps-maintains-healthy-sugar-levels--helps-in-weight-management---1l--501050',
 '/health-care/products/dr-morepen-gluco-one-bg-03-glucometer-test-strips-box-of-50-172151',
 '/health-care/products/accu-chek-active-glucometer-test-strips-box-of-50-172157',
 '/health-care/products/pharmeasy-diabetic-protein-powder-chocolate-flavour-400g-3963859',
 '/health-care/products/accu-chek-instant-glucometer-test-strips-box-of-50-206937',
 '/health-care/products/liveasy-foods-healthy-seed-mix-3515408',
 '/health-care/products/gelusil-mps-mint-flavour-sugar-free-bottle-of-400ml-liquid-208203',
 '/health-care/products/everherb-flaxseed-omega-3---essential-fatty-acids---healthy-heart---bottle-of-60-237191',
 '/health-care/products/contour-plus-glucometer-test-strips-box-of-50-4461',
 '/health-care/products/liveasy-foods-healthy-seed-mix--blend-of-6-fibre-rich-healthy-seeds-499566',
 '/health-care/products/one-touch-select-glucometer-test-strips-bottle-of-50-15466',
 '/health-care/products/pharmeasy-apple-cider-vinegar-with-mother--improves-metabolism--500ml-bottle-3864231',
 '/health-care/products/accu-chek-active-glucometer-test-strips-box-of-100-172158',
 '/health-care/products/digene-gel-acidity-gas-relief---200ml-mint-flavour-172824',
 '/health-care/products/cremaffin-constipation-relief-syrup-mint-225ml-175750',
 '/health-care/products/one-touch-select-plus-glucometer-test-strips-box-of-50-230432',
 '/health-care/products/sugar-free-gold-pellet-500-no-s-3669245',
 '/health-care/products/pharmeasy-coenzyme-q10-coq10-200mg-with-piperine---for-heart-health-bottle-of-60-capsules-4315302',
 '/health-care/products/pharmeasy-fish-oil-1000mg-soft-gelatin-60-capsules-4149275',
 '/health-care/products/everherb-flaxseed-omega-3---essential-fatty-acids---healthy-heart---bottle-of-60-237191',
 '/health-care/products/seacod-cap-100-s-23935',
 '/health-care/products/pharmeasy-apple-cider-vinegar-with-mother--improves-metabolism--500ml-bottle-3864231',
 '/health-care/products/everherb-fat-burner---natural-herbal-blend---accelerates-calorie-burning---bottle-of-60-237462',
 '/health-care/products/hima-arjuna-tablet-60-s-12828',
 '/health-care/products/wow-life-science-omega-3-capsules-bottle-of-60-237224',
 '/health-care/products/omron-hem-7120-bp-monitor-175456',
 '/health-care/products/baidyanath-nagpur-amla-juice---natural-immunity-booster-enriched-with-vitamin-c---1-ltr-3688561',
 '/health-care/products/briyo-fish-oil-mini-450-mg-size--60-softgels---71-39-omega-3-320-mg-omega-3-per-450-mg-capsule-3737089',
 '/health-care/products/healthkart-hk-vitals-fish-oil-capsule-1000mg-omega-3-180-mg-epa-120-mg-dha-90-capsules-3900337',
 '/health-care/products/omron-hem-7124-bp-monitor-223948',
 '/health-care/products/himalaya-lasuna-tablets---60-s-12897',
 '/health-care/products/healthkart-hk-vitals-fish-oil-1000mg-with-180mg-epa-and-120mg-dha-60-capsules-3828218',
 '/health-care/products/dr-morepen-bp-15-bp-monitor-3572012',
 '/health-care/products/seacod-cod-liver-oil-bottle-of-60-ml-24034',
 '/health-care/products/dr-morepen-omega-3-deep-sea-fish-oil-triple-strength-capsules-for-healthy-heart-brain-joints---60-softgels-3512184',
 '/health-care/products/accusure-as-bp-digital-monitor-3012587',
 '/health-care/products/kapiva-dia-free-juice-2l-for-holistic-diabetes-care-amla-karela-9-more---super-saver-pack-of-2-3864283',
 '/health-care/products/everherb-karela-jamun-juice---helps-maintains-healthy-sugar-levels--helps-in-weight-management---1l--501050',
 '/health-care/products/healthvit-keto-fat-burner-formulated-in-usa-with-garcinia-green-tea-green-coffee-cla--60-capsules-502201',
 '/health-care/products/everherb-giloy-tulsi-juice---strengthens-body-defence-system---natural-immunity-booster---1-litre-501053',
 '/health-care/products/himalaya-liv-52-tablet-pack-of-2-3884334',
 '/health-care/products/everherb-amla-juice-rich-in-vitamin-c-natural-immunity-booster---1-litre-bottle-501052',
 '/health-care/products/herbal-hills-gotu-kola-powder---1-kg-3808960',
 '/health-care/products/torliv-200ml-pack-of-6-4075684',
 '/health-care/products/herbal-hills-guduchi-powder---1kg---pack-of-2-3628748',
 '/health-care/products/healthvit-ginger-powder-250-mg--60-capsules-502194',
 '/health-care/products/kerala-ayurveda-ajax-vigor-improvement-capsules-box-of-50-s-216505',
 '/health-care/products/dr-vaidya-s-herbo24turbo-capsules-ayurvedic-shilajit-vitalizer-for-men-30-capsules-216335',
 '/health-care/products/herbal-hills-turmeric-powder---1kg---pack-of-2-3629912',
 '/health-care/products/dr-vaidya-s-cycloherb-capsule-30-3018418',
 '/health-care/products/axiom-karela-jamun-swaras-500-ml-3027230',
 '/health-care/products/torliv-200ml-pack-of-3-4075683',
 '/health-care/products/hass-shunthi-churna---shunthi-powder---dry-ginger-powder--for-tea-for-throat-1x500-gram--3825744',
 '/health-care/products/herbal-hills-nagarmotha-powder---1kg---pack-of-2-3628852',
 '/health-care/products/anuja-actiliv-forte-tablet---60-tab-pack-of-2--3789527',
 '/health-care/products/dr-vaidya-s-cycloherb--for-supporting-female-reproductive-health-30-capsules-x-2--3113918',
 '/health-care/products/organic-india-assam-black-tea-50-tea-bags-4337954',
 '/health-care/products/equalstwo-baby-skin-healing-cream-150-gm-3845815',
 '/health-care/products/equalstwo-baby-moisturizer-200-ml-3845371',
 '/health-care/products/prega-news-pregnancy-test-kit-177505',
 '/health-care/products/ultra-d3-drops---vitamin-d3-for-infants-vitamin-drops-bottle-of-15-ml-227487',
 '/health-care/products/i-can-pregnancy-test-kit-88380',
 '/health-care/products/tedibar-baby-soap-box-of-75-g-x-2-235076',
 '/health-care/products/new-atogla-baby-moisturizing-lotion-bottle-of-200-ml-3754509',
 '/health-care/products/ferronomic-plus-tablet-15-no-s-4085848',
 '/health-care/products/himalaya-baby-powder-bottle-of-400-g-175638',
 '/health-care/products/prohance-mom-chocolate-nutrition-drink-jar-of-400-g-193671',
 '/health-care/products/sebamed-baby-cleansing-bar---100g-28421',
 '/health-care/products/tedibar-bathing-bar-75gm-7483',
 '/health-care/products/enterogermina-probiotic-supplement-for-diarrhea-treatment-restoration-of-gut-flora-for-kids-adults-oral-use---2-strips-4-capsules-each--45590',
 '/health-care/products/pharmeasy-multivitamin-gummies-3626268',
 '/health-care/products/spoo-shampoo-bottle-of-125-ml-192679',
 '/health-care/products/b4-nappi-baby-rash-cream-tube-of-75-g-7497',
 '/health-care/products/tedibar-baby-soap-box-of-75-g-x-3-2982412',
 '/health-care/products/aptamil-stage-1-infant-formula-baby-food-tin-of-400-g-192264',
 '/health-care/products/pharmeasy-multivitamin-women---bottle-of-60-3662202',
 '/health-care/products/aptamil-baby-food-stage-2-follow-up-formula-box-of-400-g-192265',
 '/health-care/products/liveasy-adult-diaper-m-size-28-45-inch-tape-style-diapers-10s-4059719',
 '/health-care/products/calcimax-forte-plus-strip-of-30-tablets-19501',
 '/health-care/products/pharmeasy-knee-cap---black--large-3648956',

In [61]:
final_scrapped_values={
    "title":[],"category":[],"price":[],"no_of_ratings_given":[],"product_offer":[]
}

def scrapping_values(links):

    for i in range(len(links)):
        url=f"https://pharmeasy.in{links[i]}"
        r=requests.get(url)
        html_docs=r.text

        soup=BeautifulSoup(html_docs,"html.parser")

        #title
        h1=soup.h1
        final_scrapped_values["title"].append(h1.get_text(strip=True) if h1 else None)

        # category
        a_tag=soup.find_all("a",class_="BreadCrumbLink_breadCrumb___OJ18")
        final_scrapped_values["category"].append(a_tag[1].get_text(strip=True) if len(a_tag)>1 else None)

        # price
        price_tag=soup.find("div",class_="ProductPriceContainer_mrp___GtBV")
        final_scrapped_values["price"].append(price_tag.get_text(strip=True) if price_tag else None)

        #ratings
        rating_tag=soup.find("div",class_="OverviewSection_ratingText__qUpG6")
        final_scrapped_values["no_of_ratings_given"].append(rating_tag.get_text(strip=True) if rating_tag else None)

        #offers
        offer=soup.find("div",class_="ProductPriceContainer_discountContainer__5arLQ")
        final_scrapped_values["product_offer"].append(offer.get_text(strip=True) if offer else None)

    return final_scrapped_values

In [62]:
data=scrapping_values(all_links)

In [63]:
import pandas as pd

In [64]:
df=pd.DataFrame(data)

In [65]:
df

,title,category,price,no_of_ratings_given,product_offer
0,Pharmeasy Coenzyme Q10 (Coq10) 200mg With Pipe...,Healthcare,₹770.65,None,53% OFF
1,Pharmeasy Diabetic Protein Powder French Vanil...,Healthcare,₹382.27,(60ratings),57% OFF
2,Everherb Karela Jamun Juice - Helps Maintains ...,Healthcare,₹160.85,(2174ratings),57% OFF
3,Everherb Diabetic Care Juice-13 Potent Herbs -...,Healthcare,₹230.42,(1429ratings),59% OFF
4,Pharmeasy Pill Box Organizer,Healthcare,₹234.53,(905ratings),53% OFF
...,...,...,...,...,...
315,Hk Vitals Biotin (60 Tablets) | Supplement For...,Healthcare,₹361.13,(6ratings),23% OFF
316,Accusure Fetal Doppler For Doctors And Mothers...,Healthcare,₹2001,(12ratings),71% OFF
317,Dr. Biswas Good Health Strong Capsule (Pack Of 2),Healthcare,₹211.2,(31ratings),56% OFF
318,Kapiva Himalayan Shilajit/Shilajeet Resin 40g ...,Healthcare,₹1648.9,None,45% OFF
319,Wellbeing Nutrition Skin Fuel Japanese Collage...,Healthcare,₹5124.3,None,5% OFF

In [66]:
df.to_csv("myData.csv",index=False)

In [67]:
pharmeasy= {
    "title": [...],
    "category": [...],
    "price": [...],
    "no_of_ratings_given": [...],
    "product_offer": [...]
}

In [68]:
def scrape_all_pages():

    for page_index in range(16):

        file_path = f"data/page{page_index}.html"

        if not os.path.exists(file_path):
            print(f"Missing file: {file_path}")
            continue

        with open(file_path, "r", encoding="utf-8") as f:
            html_docs = f.read()

        soup = BeautifulSoup(html_docs, "html.parser")

        #Extract category
        breadcrumbs = soup.find_all("a", class_="BreadCrumbLink_breadCrumb___OJ18")
        category = breadcrumbs[2].get_text(strip=True) if len(breadcrumbs) > 2 else None

        #Product Links
        product_links = []

        for card in soup.find_all(class_="ProductCard_productCardWrapper__x7Ehg"):
            a_tag = card.find("a")
            if a_tag and a_tag.get("href"):
                product_links.append(a_tag.get("href"))

        # Visiting product
        for link in product_links:

            product_url = "https://pharmeasy.in" + link
            r = requests.get(product_url)

            if r.status_code != 200:
                continue

            product_soup = BeautifulSoup(r.text, "html.parser")

            # title
            h1 = product_soup.h1
            pharmeasy["title"].append(
                h1.get_text(strip=True) if h1 else None
            )

            # category
            pharmeasy["category"].append(category)

            # price
            price_tag = product_soup.find(
                "div", class_="ProductPriceContainer_mrp___GtBV"
            )
            pharmeasy["price"].append(
                price_tag.get_text(strip=True) if price_tag else None
            )

            # ratings
            rating_tag = product_soup.find(
                "div", class_="OverviewSection_ratingText__qUpG6"
            )
            pharmeasy["no_of_ratings_given"].append(
                rating_tag.get_text(strip=True) if rating_tag else None
            )

            # offer
            offer_tag = product_soup.find(
                "div", class_="ProductPriceContainer_discountContainer__5arLQ"
            )
            pharmeasy["product_offer"].append(
                offer_tag.get_text(strip=True) if offer_tag else None
            )

    return pharmeasy

In [69]:
pharmeasy_data=scrape_all_pages()

In [70]:
df1=pd.DataFrame(pharmeasy)

In [71]:
df1.to_csv("pharmeasy.csv",index=False)

In [72]:
df1

,title,category,price,no_of_ratings_given,product_offer
0,Ellipsis,Ellipsis,Ellipsis,Ellipsis,Ellipsis
1,Pharmeasy Coenzyme Q10 (Coq10) 200mg With Pipe...,Must Haves,₹770.65,None,53% OFF
2,Pharmeasy Diabetic Protein Powder French Vanil...,Must Haves,₹382.27,(60ratings),57% OFF
3,Everherb Karela Jamun Juice - Helps Maintains ...,Must Haves,₹160.85,(2174ratings),57% OFF
4,Everherb Diabetic Care Juice-13 Potent Herbs -...,Must Haves,₹230.42,(1429ratings),59% OFF
...,...,...,...,...,...
316,Hk Vitals Biotin (60 Tablets) | Supplement For...,Explore More,₹361.13,(6ratings),23% OFF
317,Accusure Fetal Doppler For Doctors And Mothers...,Explore More,₹2001,(12ratings),71% OFF
318,Dr. Biswas Good Health Strong Capsule (Pack Of 2),Explore More,₹211.2,(31ratings),56% OFF
319,Kapiva Himalayan Shilajit/Shilajeet Resin 40g ...,Explore More,₹1648.9,None,45% OFF
320,Wellbeing Nutrition Skin Fuel Japanese Collage...,Explore More,₹5124.3,None,5% OFF

In [73]:
df1.drop(0,inplace=True)

In [74]:
df1.reset_index(drop=True,inplace=True)

In [75]:
df1

,title,category,price,no_of_ratings_given,product_offer
0,Pharmeasy Coenzyme Q10 (Coq10) 200mg With Pipe...,Must Haves,₹770.65,None,53% OFF
1,Pharmeasy Diabetic Protein Powder French Vanil...,Must Haves,₹382.27,(60ratings),57% OFF
2,Everherb Karela Jamun Juice - Helps Maintains ...,Must Haves,₹160.85,(2174ratings),57% OFF
3,Everherb Diabetic Care Juice-13 Potent Herbs -...,Must Haves,₹230.42,(1429ratings),59% OFF
4,Pharmeasy Pill Box Organizer,Must Haves,₹234.53,(905ratings),53% OFF
...,...,...,...,...,...
315,Hk Vitals Biotin (60 Tablets) | Supplement For...,Explore More,₹361.13,(6ratings),23% OFF
316,Accusure Fetal Doppler For Doctors And Mothers...,Explore More,₹2001,(12ratings),71% OFF
317,Dr. Biswas Good Health Strong Capsule (Pack Of 2),Explore More,₹211.2,(31ratings),56% OFF
318,Kapiva Himalayan Shilajit/Shilajeet Resin 40g ...,Explore More,₹1648.9,None,45% OFF
319,Wellbeing Nutrition Skin Fuel Japanese Collage...,Explore More,₹5124.3,None,5% OFF

In [76]:
df1.to_csv("pharmeasy.csv", index=False)